### ISSUE TITLE
Stop Parallax after some scroll to especific position

### ISSUE THREAD

**Issue by pisandelli** [markdalgleish/stellar.js#102]
Hi! First Stellar is simply **AWESOME!**
I just want to know how can I stop the effect after scrolling to a pre-determined position.
I have a div changing its position and I want to stop parallax after it get in the center of the screen.
How can I achieve this?

Thanks in Advance

Regards,

**Comment by imthat** [comment]
I'm also trying to find a way to stop updating positions when the parallax element is out of view, it really slows down the performance, I think this is a major feature that needs to be added.

**Comment by yuqiandoudou** [comment]
Would you mind explain the term "Parallax element?

------------------ 原始邮件 ------------------
发件人: "imthat";notifications@github.com;
发送时间: 2015年7月11日(星期六) 下午3:38
收件人: "markdalgleish/stellar.js"stellar.js@noreply.github.com; 

主题: Re: [stellar.js] Stop Parallax after some scroll to especificposition (#102)

I also want to stop updating positions when the parallax element is out of view, I think this is a major feature needs to be added, it really slows down the performance.

**Comment by imthat** [comment]
I mean the html element that implements parallax effect, without a stop or destroy method, function will continue to update the parallax position even when the element is not in the view.
