### ISSUE TITLE
Make Stellar.js available on NPM

### ISSUE THREAD

**Issue by selbekk** [markdalgleish/stellar.js#130]
Title says it all, really. I use Browserify to handle my frontend code, and would love to run "npm run jquery.stellar" and include it in my files the same way. 

No pull request needed really, just run `npm publish` and enjoy great success

**Comment by markdalgleish** [comment]
I don't maintain this project anymore. You can install from GitHub with `npm install --save markdalgleish/stellar.js#v0.6.2`.
