### ISSUE TITLE
avoid jitter without using fixed position

### ISSUE THREAD

**Issue by m9dfukc** [markdalgleish/stellar.js#17]
hey,

I made some parallax animations using stellar.js ... in Chrome everything looks fine but using other browsers there is some heavy jittering (for all elements using a ratio below 1). Looking through the documentation there is written that position: fixed should be used to avoid that ... unfortunately position fixed isn't an option as I would lose the possibility to do relative positioning to the "mother" element. Is there some workaround or do you have some tips how to avoid the stutter without using a fixed position?

thanks

**Comment by Lucaz5520** [comment]
Wow I am 2 years late but I ran into this question and had the same situation tonight where I needed to stop the jitter but **without using position: fixed** and I have found a solution and hope this helps anyone else out there.

So I was using **GreenSock's TweenMax** building some cool stuff when I noticed that when it's "ScrollToPlugin" is activated it does not cause the elements to jitter even when they have a ration below 1. So all you would need to do (at least in my case) is to use a **smooth scrolling feature** and it will stop the jitters.

Include **TweenMax** & **ScrollToPlugin** then use this piece of code
 (These 2 assets can be found [HERE](https://github.com/greensock/GreenSock-JS) )

```
$(function(){

    var $window = $(window);        //Window object

    var scrollTime = 1.2;           //Scroll time
    var scrollDistance = 170;       //Distance. Use smaller value for shorter scroll and greater value for longer scroll

    $window.on("mousewheel DOMMouseScroll", function(event){

        event.preventDefault(); 

        var delta = event.originalEvent.wheelDelta/120 || -event.originalEvent.detail/3;
        var scrollTop = $window.scrollTop();
        var finalScroll = scrollTop - parseInt(delta*scrollDistance);

        TweenMax.to($window, scrollTime, {
            scrollTo : { y: finalScroll, autoKill:true },
                ease: Power1.easeOut,   //For more easing functions see http://api.greensock.com/js/com/greensock/easing/package-detail.html
                autoKill: true,
                overwrite: 5                            
            });

    });

});
```

Hope this helps someome
