### ISSUE TITLE
Disabling Stellar on Mobile Devices

### ISSUE THREAD

**Issue by Giovanni-Mattucci** [markdalgleish/stellar.js#37]
So I'm trying to a figure out the best way to disable Stellar for mobile devices, or even disable certain Stellar elements. 

I know there is a tutorial on how to get stellar to work on a webkit based mobile device, however there are some performance issues coming up, and it looks like disabling it all-together is the best way to go.

I'm looking at using a UA String Regex like this one: www.detectmobilebrowsers.com 

Alternatively, does anyone know what I might be able to check for using <a href="http://modernizr.com" target="_blank">Modernizr</a>? 

Thinking forward, perhaps there needs to be a function to disable stellar.js on elements from scrolling. Either set directly on the HTML object or, perhaps a hook that can be initialized from a function or if statement.

Thanks!

**Comment by andre-lergier** [comment]
I would be really interested on some feature that allow to disable Stellar.js, specially when the window is resized to a small resolution.

**Comment by sadi304** [comment]
Nowadays detecting a mobile browser is quite complicated . Using different sorts of detecting codes will not work in all the scenarios . Better use a media resolution detection with jQuery window resize function ( < 767px )  

refer to : http://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-mobile-device-in-jquery

**Comment by khromov** [comment]
@websirnik Awesome snippet! :+1:

**Comment by iamrashed01** [comment]
It's Help Me Alot, I tink You Should Try this.
var isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent) ? true : false;
if(!isMobile) {
        $(window).stellar()
}
